name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run Flask tests
        run: |
          . venv/bin/activate
          # Start de Flask server in de achtergrond
          nohup flask run --port=5000 &
          # Wacht even om ervoor te zorgen dat de server gestart is
          sleep 5
          # Voer de tests uit met pytest
          pytest

  deploy:
    needs: test  # Zorg dat de tests succesvol moeten zijn voor de deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
