name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt  # Zorg ervoor dat Flask in requirements.txt staat

    - name: Run tests with pytest
      run: |
        source venv/bin/activate
        pytest tests/test_app.py  # Run pytest in de tests folder

  deploy:
    needs: test  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build application (optioneel, als nodig voor GitHub Pages)
        run: |
          # Voeg hier een build stap toe als dat nodig is, bijvoorbeeld:
          # python setup.py install
          # of een ander buildcommando voor je app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build 
