name: Health Check & Logging Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install flask pytest requests

    - name: Start Flask App
      run: |
        nohup python app.py &
        sleep 5  # Wacht tot de server draait

    - name: Run tests
      run: pytest
      
    - name: Set up Flask environment
      run: |
        export FLASK_APP=app.py
        flask run --port=8000
    